### ISSUE TITLE
PNG Sequences Take a Long Time to Load- and Sometimes They Don't Load at All

### ISSUE THREAD

**Issue by mt-snowball** [Snowballvfx/issue-tracker#1]
We're having some issues loading PNG sequences into file.

Sometimes they load after a few seconds, sometimes they take a very long time (more than 5 minutes) and then load, and sometimes they just lock up your maya session until you decide it's time to restart. Currently I have a session of 101A-126 that's been loading its PNG sequence for 15-20 minutes (edit: it hung for about 35 minutes total). I have a lot of non-shot things to do, but for artists this means just sitting and waiting.

This seems to be more common with longer PNG sequences.

--m

**Comment by liorbenhorin** [comment]
Hey, 
This sounds like a network issue - can you make a quick test?
Copy the sequence to you local machine and try to load it in.
Please report with results. 

Can you also write down the resolution of the png sequence as well as a file size for a single image?

In general, nothing should freeze your session for more then 2-5 minutes, any longer and i would flag it as an issue here to investigate.

**Comment by mt-snowball** [comment]
- All PNG sq's are 1920*1080, and we're trying to get larger resolution ones (at exactly 1080p there's no room to widen and no bleed)
- Regardless of source, PNG sq load will sync to network, since it moves the sq to the network shot folder, (will try anyways and report back)
- Should be noted that this is happening pretty frequently, I'm just using my own shot as an example so I don't have to waste floor artists time with emails
- PNGs are around 120KB

**Comment by mt-snowball** [comment]
Sourcing from the desktop seems to work normally. However, I did notice from my crashed session that the process hung after all images were transferred successfully to the IS folder, implying that the problem happens after the images are copied to the shot directory. 

I'll have artists try it and report back if the issue reappears. Can't hurt to take one piece of network access out of the equation.

**Comment by liorbenhorin** [comment]
@mt-snowball I understand the tool is copying the images to the network, i just want you to grab a sequence and copy it to your local machine, and load it onto a card that you make in a brand new file without using any tools.

**Comment by mt-snowball** [comment]
I'd have to go through a tutorial and learn how to do that, and I'm on a high priority task right now. Is there a point to this?

**Comment by liorbenhorin** [comment]
I assumed this is a no deal for you. no worries, i will be looking at the issue on Sunday.
Mean time stay strong.

The point is of course to collect as much data as possible, since this does not sound normal - after all, our comp department use image sequences from the network all the time, and not simple PNG's, but heavy EXR's.

Thanks for reporting.

**Comment by mt-snowball** [comment]
Yeah, fair enough. I'm sure it wouldn't take too long to learn, but I'm rushing out the first shot with final PNGs.

I'll update if anything happens related to this, thanks for looking into it

**Comment by mt-snowball** [comment]
Haha, as I said that the final PNG sequence I loaded froze my maya session-

animation\101A\126_00\IS\

There are separate passes for body/tail/head (listed by the order I loaded them) it's hanging loading the head sequence. Head PNGs moved to the IS folder correctly, but somehow the body pass is no longer in the IS folder even though that sequence loaded correctly into my session?

**Comment by liorbenhorin** [comment]
Solved in snowballvfx/maya/bg_card_rig: Move the disambiguation card index from the head to the tail of a card's name for floating and floor cards
